import shutil
import subprocess
from pathlib import Path

LOADER_TEMPLATE = """\
import sys
import os

# This loader was generated by pikpak-nautilus installer
# It adds the uv-installed package to sys.path

pkg_path = "{pkg_path}"
if pkg_path not in sys.path:
    sys.path.insert(0, pkg_path)

try:
    from pikpak_nautilus.plugin import PikPakMenuProvider
except ImportError as e:
    import subprocess
    subprocess.run(['notify-send', 'PikPak Plugin Error', f'Could not load plugin: {{e}}'])
"""

DESKTOP_TEMPLATE = """\
[Desktop Entry]
Version=1.0
Name=PikPak Download
GenericName=Download Manager
Comment=Add magnet links to PikPak
Exec={wrapper_path} %u
Icon=folder-download
Terminal=false
Type=Application
Categories=Network;FileTransfer;
MimeType=x-scheme-handler/magnet;
StartupNotify=false
"""

WRAPPER_SCRIPT = """\
#!/bin/sh
exec python3 "{dialog_path}" --submit "$@"
"""


def install():
    pkg_path = str(Path(__file__).parent.parent)
    dialog_path = str(Path(__file__).parent / "dialog.py")

    # Install Nautilus extension loader
    ext_dir = Path.home() / ".local/share/nautilus-python/extensions"
    ext_dir.mkdir(parents=True, exist_ok=True)
    loader_file = ext_dir / "pikpak_nautilus_loader.py"
    loader_file.write_text(LOADER_TEMPLATE.format(pkg_path=pkg_path))
    print(f"Installed Nautilus extension: {loader_file}")

    # Install wrapper script to ~/.local/bin
    bin_dir = Path.home() / ".local/bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    wrapper_path = bin_dir / "pikpak-add"
    wrapper_path.write_text(WRAPPER_SCRIPT.format(dialog_path=dialog_path))
    wrapper_path.chmod(0o755)
    print(f"Installed wrapper script: {wrapper_path}")

    # Install .desktop file for pikpak:// URL scheme
    apps_dir = Path.home() / ".local/share/applications"
    apps_dir.mkdir(parents=True, exist_ok=True)
    desktop_file = apps_dir / "pikpak-handler.desktop"
    desktop_file.write_text(DESKTOP_TEMPLATE.format(wrapper_path=wrapper_path))
    print(f"Installed URL handler: {desktop_file}")

    # Register as magnet: handler
    subprocess.run(['xdg-mime', 'default', 'pikpak-handler.desktop', 'x-scheme-handler/magnet'],
                   capture_output=True)
    subprocess.run(['update-desktop-database', str(apps_dir)], capture_output=True)
    print("Registered as magnet: handler")

    print("\nPlease restart Nautilus: nautilus -q")


def uninstall():
    loader_file = Path.home() / ".local/share/nautilus-python/extensions/pikpak_nautilus_loader.py"
    desktop_file = Path.home() / ".local/share/applications/pikpak-handler.desktop"
    wrapper_file = Path.home() / ".local/bin/pikpak-add"

    removed = False
    for f, name in [(loader_file, "Nautilus extension"),
                    (desktop_file, "URL handler"),
                    (wrapper_file, "wrapper script")]:
        if f.exists():
            f.unlink()
            print(f"Removed {name}")
            removed = True

    if not removed:
        print("Nothing to uninstall")
