import os
import sys
from pathlib import Path

LOADER_TEMPLATE = """
import sys
import os

# This loader was generated by pikpak-nautilus installer
# It adds the uv-installed package to sys.path

pkg_path = "{pkg_path}"
if pkg_path not in sys.path:
    sys.path.insert(0, pkg_path)

try:
    from pikpak_nautilus.plugin import PikPakMenuProvider
except ImportError as e:
    import subprocess
    subprocess.run(['notify-send', 'PikPak Plugin Error', f'Could not load plugin: {{e}}'])
"""

def install():
    # 1. 确定插件目录
    ext_dir = Path.home() / ".local/share/nautilus-python/extensions"
    ext_dir.mkdir(parents=True, exist_ok=True)
    
    # 2. 获取当前包所在的 site-packages 路径
    # 当作为 uv tool install 时，__file__ 会指向工具的虚拟环境
    pkg_path = str(Path(__file__).parent.parent)
    
    # 3. 写入加载器
    loader_file = ext_dir / "pikpak_nautilus_loader.py"
    with open(loader_file, "w") as f:
        f.write(LOADER_TEMPLATE.format(pkg_path=pkg_path))
    
    print(f"Successfully installed Nautilus extension loader to {loader_file}")
    print("Please restart Nautilus with 'nautilus -q' to apply changes.")

def uninstall():
    loader_file = Path.home() / ".local/share/nautilus-python/extensions/pikpak_nautilus_loader.py"
    if loader_file.exists():
        loader_file.unlink()
        print("Extension uninstalled.")
    else:
        print("Extension not found.")
